### 1、用户发起提现10元
POST http://localhost:8080/cashOut
Accept: application/json
Content-Type: application/json

{
  "accountId": 1,
  "price": "10.00"
}

### 2、模拟第三方支付-提现成功回调
POST http://localhost:8080/cashOutCallback
Accept: application/json
Content-Type: application/json

{
  "cashOutId": 1,
  "success": true
}

### 3、模拟第三方支付-提现失败回调
POST http://localhost:8080/cashOutCallback
Accept: application/json
Content-Type: application/json

{
  "cashOutId": 2,
  "success": false,
  "failMsg": "账户余额不足"
}