spring:
  cloud:
    gateway:
      routes:
        - id: lesson042-service1
          uri: http://localhost:8081
          predicates:
            - Path=/lesson042-service1/**
          filters:
            - StripPrefix=1
server:
  port: 8080