### 1.普通版本
POST http://localhost:8080/article/publish
Content-Type: application/json
Accept: application/json

{"content": "哈哈哈，路人"}


### 2.责任链版本
POST http://localhost:8080/article/publishNew
Content-Type: application/json
Accept: application/json

{"content": "哈哈哈"}