spring:
  application:
    name: lesson052
server:
  # 停机方式，immediate：立即停机，默认值；graceful：优雅停机
  shutdown: graceful


#management:
#  endpoint:
#    shutdown:
#      enabled: true
#  endpoints:
#    web:
#      base-path: /actuator
#      exposure:
#        include: shutdown



