server:
  port: 8080
spring:
  application:
    name: lesson001
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/luren?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root123
  sql:
    init:
      schema-locations: classpath:db/init.sql
      mode: always
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 1000MB
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml

shard-upload:
  file-path: ${SHARD_UPLOAD_PATH:./uploads/}
  chunk-size: 1048576
  # 启用并发合并的最小分片数量阈值
  concurrent-merge-threshold: 10
  # 并发合并时的批次大小
  merge-batch-size: 5

logging:
  level:
    com:
      itsoku: debug
